# Generated by Django 3.2.6 on 2021-10-16 19:44

from django.db import migrations, models
import trips.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city', models.CharField(blank=True, max_length=30, verbose_name='city')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'city',
                'verbose_name_plural': 'cities',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country', models.CharField(blank=True, max_length=30, verbose_name='country')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'country',
                'verbose_name_plural': 'countries',
            },
        ),
        migrations.CreateModel(
            name='Days',
            fields=[
                ('day_from', models.DateField()),
                ('day_to', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('content', models.TextField(blank=True, null=True, verbose_name='what would you like to do?')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'description',
                'verbose_name_plural': 'descriptions',
                'ordering': ('content',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag', models.CharField(blank=True, max_length=20, verbose_name='Tag Name')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('short_description', models.CharField(blank=True, max_length=64, null=True, verbose_name='short_description')),
                ('trip_images', models.ImageField(blank=True, default='', max_length=255, null=True, upload_to=trips.models.get_trip_image_filepath)),
                ('created', models.DateField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TripPlan',
            fields=[
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Trip Plan Name')),
                ('is_private', models.BooleanField(default=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TripPlanGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_edit_perm', models.BooleanField(default=True)),
            ],
        ),
    ]
