# Generated by Django 3.2.6 on 2021-09-15 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripplangroup',
            name='profiles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tripplangroup',
            name='trip_plan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trips.tripplan'),
        ),
        migrations.AddField(
            model_name='tripplan',
            name='members',
            field=models.ManyToManyField(related_name='trip_members', through='trips.TripPlanGroup', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tripplan',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trip',
            name='cities',
            field=models.ManyToManyField(related_name='cities', to='trips.City'),
        ),
        migrations.AddField(
            model_name='trip',
            name='countries',
            field=models.ManyToManyField(related_name='countries', to='trips.Country'),
        ),
        migrations.AddField(
            model_name='trip',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.tripplan'),
        ),
        migrations.AddField(
            model_name='trip',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='trips.Tag'),
        ),
        migrations.AddField(
            model_name='description',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.trip'),
        ),
        migrations.AddField(
            model_name='days',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.trip'),
        ),
    ]
