# Generated by Django 3.2.6 on 2021-09-16 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='tags',
        ),
        migrations.AddField(
            model_name='tripplan',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='trips.Tag'),
        ),
        migrations.AlterField(
            model_name='tripplan',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Trip Plan Name'),
        ),
    ]
