# Generated by Django 3.2.6 on 2021-09-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_auto_20210921_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city',
            field=models.CharField(blank=True, max_length=30, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='country',
            name='country',
            field=models.CharField(blank=True, max_length=30, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(blank=True, max_length=20, verbose_name='tag name'),
        ),
    ]
